newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖


  Thank you and congrats🎉 for opening your first pull request.


  Bluelearn is India’s smartest student community!


  Join niche clubs, interact with experts, explore, network with high-profile and ambitious individuals, get internships all for free! What are you waiting for?


  [Join discord server here](https://discord.gg/8yTvfJq2)
  
  
firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉🎉🎉
  

newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!
